when:
  event: [push, pull_request]
  branch: [main, develop]

steps:
  test:
    name: Test Python ${{ matrix.python-version }}
    image: python:${{ matrix.python-version }}
    matrix:
      python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    commands:
      - pip install poetry
      - poetry config virtualenvs.create false
      - poetry install --no-interaction
      - poetry run flake8 keyrunes_sdk tests
      - poetry run mypy keyrunes_sdk
      - poetry run pytest tests/ -v --cov=keyrunes_sdk --cov-report=xml --cov-report=term

  format-check:
    name: Check code formatting
    image: python:3.14
    commands:
      - pip install poetry
      - poetry config virtualenvs.create false
      - poetry install --no-interaction
      - poetry run black --check keyrunes_sdk tests examples
      - poetry run isort --check-only keyrunes_sdk tests examples
