"""Property-based tests for the Keyrunes SDK using Hypothesis.

These tests assert invariants that must hold for every input in a domain,
rather than for a handful of hand-picked examples. They complement the
example-based suites in ``test_client.py`` / ``test_models.py`` and are the
main defence against the mutants generated by ``mutmut``.
"""

from typing import Any, Dict
from unittest.mock import MagicMock

import pytest
from hypothesis import HealthCheck, assume, given, settings
from hypothesis import strategies as st
from pydantic import ValidationError

from keyrunes_sdk.client import KeyrunesClient
from keyrunes_sdk.exceptions import (
    AuthenticationError,
    AuthorizationError,
    NetworkError,
    UserNotFoundError,
)
from keyrunes_sdk.models import (
    AdminRegistration,
    GroupCheck,
    LoginCredentials,
    Token,
    User,
    UserRegistration,
)

# These tests build httpx clients, so keep deadlines off and allow
# function-scoped fixtures to be reused across examples. The number of
# examples is governed by the Hypothesis profile selected in ``conftest.py``
# (``HYPOTHESIS_PROFILE``), so that a mutation run can trade breadth for speed.
PROPERTY_SETTINGS = settings(
    deadline=None,
    suppress_health_check=[
        HealthCheck.function_scoped_fixture,
        # mutmut re-runs the suite in a single process, which trips this.
        HealthCheck.differing_executors,
    ],
)

# Hostnames must stay inside the character set ``urljoin`` treats as authority,
# otherwise the generated URL is not the one under test.
hostnames = st.builds(
    lambda labels: ".".join(labels),
    st.lists(
        st.text(
            alphabet=st.characters(
                whitelist_categories=("Ll", "Nd"), max_codepoint=122
            ),
            min_size=1,
            max_size=12,
        ),
        min_size=1,
        max_size=3,
    ),
)

# A conservative "safe text" strategy: printable, no surrogates, no control
# characters that would make an HTTP header or a URL invalid.
safe_text = st.text(
    alphabet=st.characters(
        min_codepoint=32, max_codepoint=126, blacklist_categories=("Cs",)
    ),
    min_size=1,
    max_size=40,
)

group_names = st.text(
    alphabet=st.characters(
        min_codepoint=48, max_codepoint=122, blacklist_categories=("Cs",)
    ),
    min_size=1,
    max_size=20,
)


def _make_client(
    base_url: str = "https://keyrunes.example.com",
) -> KeyrunesClient:
    """Build a client whose transport is mocked out."""
    client = KeyrunesClient(base_url=base_url)
    client._make_request = MagicMock()
    return client


class TestBaseUrlNormalization:
    """``KeyrunesClient`` must normalize the base URL deterministically."""

    @given(host=hostnames, slashes=st.integers(min_value=0, max_value=8))
    @PROPERTY_SETTINGS
    def test_trailing_slashes_are_always_stripped(
        self, host: str, slashes: int
    ) -> None:
        raw = f"https://{host}" + "/" * slashes
        client = KeyrunesClient(base_url=raw)
        assert not client.base_url.endswith("/")
        assert client.base_url == f"https://{host}"
        client.close()

    @given(host=hostnames, slashes=st.integers(min_value=0, max_value=8))
    @PROPERTY_SETTINGS
    def test_normalization_is_idempotent(self, host: str, slashes: int) -> None:
        raw = f"https://{host}" + "/" * slashes
        once = KeyrunesClient(base_url=raw)
        twice = KeyrunesClient(base_url=once.base_url)
        assert once.base_url == twice.base_url
        once.close()
        twice.close()


class TestNormalizeUserInvariants:
    """Invariants of :meth:`KeyrunesClient._normalize_user`."""

    @given(
        user_id=safe_text,
        username=safe_text,
        email=st.emails(),
        fallback_num=st.integers(min_value=1, max_value=10**9),
        external=safe_text,
    )
    @PROPERTY_SETTINGS
    def test_id_precedence_prefers_id_over_user_id_and_external_id(
        self,
        user_id: str,
        username: str,
        email: str,
        fallback_num: int,
        external: str,
    ) -> None:
        payload = {
            "id": user_id,
            "user_id": fallback_num,
            "external_id": external,
            "username": username,
            "email": email,
        }
        user = KeyrunesClient._normalize_user(payload)
        assert user.id == str(user_id)

    @given(
        username=safe_text,
        email=st.emails(),
        fallback_num=st.integers(min_value=1, max_value=10**9),
        external=safe_text,
    )
    @PROPERTY_SETTINGS
    def test_user_id_wins_when_id_absent(
        self,
        username: str,
        email: str,
        fallback_num: int,
        external: str,
    ) -> None:
        payload = {
            "user_id": fallback_num,
            "external_id": external,
            "username": username,
            "email": email,
        }
        user = KeyrunesClient._normalize_user(payload)
        assert user.id == str(fallback_num)

    @given(
        username=safe_text,
        email=st.emails(),
        external=safe_text,
    )
    @PROPERTY_SETTINGS
    def test_external_id_is_the_last_resort(
        self, username: str, email: str, external: str
    ) -> None:
        payload = {
            "external_id": external,
            "username": username,
            "email": email,
        }
        user = KeyrunesClient._normalize_user(payload)
        assert user.id == str(external)

    @given(
        groups=st.lists(group_names, max_size=6),
        flag=st.booleans(),
        email=st.emails(),
    )
    @PROPERTY_SETTINGS
    def test_is_admin_matches_its_specification(
        self, groups: list, flag: bool, email: str
    ) -> None:
        payload = {
            "id": "u1",
            "username": "u",
            "email": email,
            "groups": groups,
            "is_admin": flag,
        }
        user = KeyrunesClient._normalize_user(payload)
        expected = flag or any("admin" in str(g).lower() for g in groups)
        assert user.is_admin is expected

    @given(
        groups=st.lists(group_names, min_size=1, max_size=6), email=st.emails()
    )
    @PROPERTY_SETTINGS
    def test_any_group_containing_admin_grants_admin(
        self, groups: list, email: str
    ) -> None:
        assume(not any("admin" in g.lower() for g in groups))
        payload = {
            "id": "u1",
            "username": "u",
            "email": email,
            "groups": groups + ["Platform-ADMIN-team"],
            "is_admin": False,
        }
        user = KeyrunesClient._normalize_user(payload)
        assert user.is_admin is True

    @given(email=st.emails())
    @PROPERTY_SETTINGS
    def test_null_groups_normalize_to_empty_list(self, email: str) -> None:
        payload = {
            "id": "u1",
            "username": "u",
            "email": email,
            "groups": None,
        }
        user = KeyrunesClient._normalize_user(payload)
        assert user.groups == []

    @given(
        groups=st.lists(group_names, max_size=6),
        email=st.emails(),
        active=st.booleans(),
    )
    @PROPERTY_SETTINGS
    def test_round_trip_through_normalize_is_stable(
        self, groups: list, email: str, active: bool
    ) -> None:
        payload = {
            "id": "u1",
            "username": "u",
            "email": email,
            "groups": groups,
            "is_active": active,
        }
        first = KeyrunesClient._normalize_user(payload)
        second = KeyrunesClient._normalize_user(first.model_dump())
        assert first.id == second.id
        assert first.groups == second.groups
        assert first.is_active == second.is_active is active
        assert first.is_admin == second.is_admin


class TestTokenParsingInvariants:
    """Invariants of :meth:`KeyrunesClient._parse_token_response`."""

    @given(token=safe_text, expires=st.integers(min_value=0, max_value=10**6))
    @PROPERTY_SETTINGS
    def test_new_format_maps_token_to_access_token(
        self, token: str, expires: int
    ) -> None:
        client = _make_client()
        payload: Dict[str, Any] = {"token": token, "expires_in": expires}
        parsed = client._parse_token_response(payload)
        assert parsed.access_token == token
        assert parsed.token_type == "bearer"
        assert parsed.expires_in == expires
        client.close()

    @given(token=safe_text, token_type=safe_text)
    @PROPERTY_SETTINGS
    def test_legacy_format_is_preserved_verbatim(
        self, token: str, token_type: str
    ) -> None:
        client = _make_client()
        payload: Dict[str, Any] = {
            "access_token": token,
            "token_type": token_type,
        }
        parsed = client._parse_token_response(payload)
        assert parsed.access_token == token
        assert parsed.token_type == token_type
        client.close()

    @given(
        payload=st.dictionaries(
            st.sampled_from(["expires_in", "refresh_token", "scope", "user"]),
            st.none(),
            max_size=4,
        )
    )
    @PROPERTY_SETTINGS
    def test_payload_without_any_token_is_rejected(
        self, payload: Dict[str, Any]
    ) -> None:
        client = _make_client()
        with pytest.raises(AuthenticationError):
            client._parse_token_response(dict(payload))
        client.close()

    @given(token=safe_text, email=st.emails())
    @PROPERTY_SETTINGS
    def test_embedded_user_is_normalized_in_both_formats(
        self, token: str, email: str
    ) -> None:
        client = _make_client()
        user_payload = {
            "user_id": 42,
            "username": "u",
            "email": email,
            "groups": ["admins"],
        }
        new_style = client._parse_token_response(
            {"token": token, "user": dict(user_payload)}
        )
        legacy = client._parse_token_response(
            {"access_token": token, "user": dict(user_payload)}
        )
        assert isinstance(new_style.user, User)
        assert isinstance(legacy.user, User)
        assert new_style.user.id == legacy.user.id == "42"
        assert new_style.user.is_admin is legacy.user.is_admin is True
        client.close()


class TestRequestUrlBuilding:
    """The endpoint/base-url join must be insensitive to slash placement."""

    @given(
        host=hostnames,
        segment=st.text(
            alphabet=st.characters(min_codepoint=97, max_codepoint=122),
            min_size=1,
            max_size=12,
        ),
        leading=st.integers(min_value=0, max_value=3),
        trailing=st.integers(min_value=0, max_value=3),
    )
    @PROPERTY_SETTINGS
    def test_slash_placement_does_not_change_target_url(
        self, host: str, segment: str, leading: int, trailing: int
    ) -> None:
        client = KeyrunesClient(base_url=f"https://{host}" + "/" * trailing)
        response = MagicMock()
        response.status_code = 200
        response.json.return_value = {}
        client._client = MagicMock()
        client._client.request.return_value = response

        client._make_request("GET", "/" * leading + f"api/{segment}")
        called_url = client._client.request.call_args.kwargs["url"]
        assert called_url == f"https://{host}/api/{segment}"


class TestErrorStatusMapping:
    """Every HTTP failure status must map to a documented SDK exception."""

    @given(status=st.integers(min_value=400, max_value=599))
    @PROPERTY_SETTINGS
    def test_status_codes_map_to_stable_exception_types(
        self, status: int
    ) -> None:
        client = KeyrunesClient(base_url="https://keyrunes.example.com")
        response = MagicMock()
        response.status_code = status
        response.json.return_value = {"error": "boom"}
        response.text = "boom"
        client._client = MagicMock()
        client._client.request.return_value = response

        expected = {
            401: AuthenticationError,
            403: AuthorizationError,
            404: UserNotFoundError,
        }.get(status, NetworkError)

        with pytest.raises(expected):
            client._make_request("GET", "/api/whatever")
        client.close()

    @given(status=st.integers(min_value=200, max_value=399))
    @PROPERTY_SETTINGS
    def test_non_error_status_codes_never_raise(self, status: int) -> None:
        client = KeyrunesClient(base_url="https://keyrunes.example.com")
        response = MagicMock()
        response.status_code = status
        response.json.return_value = {"ok": True}
        client._client = MagicMock()
        client._client.request.return_value = response

        assert client._make_request("GET", "/api/whatever") == {"ok": True}
        client.close()


class TestModelValidationBounds:
    """Pydantic constraints declared on the models must actually bite."""

    @given(
        username=st.text(min_size=3, max_size=50),
        email=st.emails(),
        password=st.text(min_size=8, max_size=64),
    )
    @PROPERTY_SETTINGS
    def test_valid_registrations_are_accepted(
        self, username: str, email: str, password: str
    ) -> None:
        registration = UserRegistration(
            username=username, email=email, password=password
        )
        assert registration.namespace == "default"
        assert registration.username == username

    @given(
        username=st.text(max_size=2),
        email=st.emails(),
        password=st.text(min_size=8, max_size=64),
    )
    @PROPERTY_SETTINGS
    def test_short_usernames_are_rejected(
        self, username: str, email: str, password: str
    ) -> None:
        with pytest.raises(ValidationError):
            UserRegistration(username=username, email=email, password=password)

    @given(
        username=st.text(min_size=51, max_size=120),
        email=st.emails(),
        password=st.text(min_size=8, max_size=64),
    )
    @PROPERTY_SETTINGS
    def test_long_usernames_are_rejected(
        self, username: str, email: str, password: str
    ) -> None:
        with pytest.raises(ValidationError):
            UserRegistration(username=username, email=email, password=password)

    @given(
        username=st.text(min_size=3, max_size=50),
        email=st.emails(),
        password=st.text(max_size=7),
    )
    @PROPERTY_SETTINGS
    def test_short_passwords_are_rejected(
        self, username: str, email: str, password: str
    ) -> None:
        with pytest.raises(ValidationError):
            UserRegistration(username=username, email=email, password=password)

    @given(
        username=st.text(min_size=3, max_size=50),
        email=st.emails(),
        password=st.text(min_size=8, max_size=64),
        admin_key=safe_text,
    )
    @PROPERTY_SETTINGS
    def test_admin_registration_inherits_user_constraints(
        self, username: str, email: str, password: str, admin_key: str
    ) -> None:
        admin = AdminRegistration(
            username=username,
            email=email,
            password=password,
            admin_key=admin_key,
        )
        assert isinstance(admin, UserRegistration)
        assert admin.admin_key == admin_key

    @given(
        username=safe_text,
        password=safe_text,
        namespace=safe_text,
    )
    @PROPERTY_SETTINGS
    def test_login_credentials_from_username_round_trip(
        self, username: str, password: str, namespace: str
    ) -> None:
        creds = LoginCredentials.from_username(username, password, namespace)
        assert creds.identity == username
        assert creds.password == password
        assert creds.namespace == namespace
        assert LoginCredentials(**creds.model_dump()) == creds

    @given(user_id=safe_text, group_id=safe_text, has_access=st.booleans())
    @PROPERTY_SETTINGS
    def test_group_check_preserves_access_flag(
        self, user_id: str, group_id: str, has_access: bool
    ) -> None:
        check = GroupCheck(
            user_id=user_id, group_id=group_id, has_access=has_access
        )
        assert check.has_access is has_access
        assert check.checked_at is not None


class TestTokenRoundTrip:
    """A ``Token`` must survive a serialize/deserialize cycle unchanged."""

    @given(
        access_token=safe_text,
        token_type=safe_text,
        expires_in=st.one_of(
            st.none(), st.integers(min_value=0, max_value=10**6)
        ),
    )
    @PROPERTY_SETTINGS
    def test_token_model_round_trip(
        self, access_token: str, token_type: str, expires_in: Any
    ) -> None:
        token = Token(
            access_token=access_token,
            token_type=token_type,
            expires_in=expires_in,
        )
        restored = Token(**token.model_dump())
        assert restored == token
